## Practice 1: Creating Arrays

**Q1.** Create a 1D array of numbers from 10 to 50 using NumPy.

In [2]:
import numpy as np
arr = np.array(range(10,51))
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


**Q2.** Create a 2D array of shape (3, 4) filled with ones.

In [3]:
arr1=np.ones((3,4))
print(arr1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**Q3.** Convert the following list to a NumPy array and print its shape:
```python
data = [[3, 5, 1], [6, 7, 9], [8, 4, 2]]
```

In [6]:
data = [[3, 5, 1], [6, 7, 9], [8, 4, 2]]
dt = np.array(data)
print(dt.shape)

(3, 3)


## Practice 2: Shape & Dimensions

**Q4.** Given an array:
```python
arr = np.array([[1, 2], [3, 4], [5, 6]])
```
- What is the shape and dimension of the array?

In [10]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.shape)
print(arr.ndim)

(3, 2)
2


## Practice 3: Reshaping and Transposing

**Q5.** Reshape the following array into a shape of (3, 3):
```python
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
reshaped = np.reshape(arr, (3,3))

**Q6.** Transpose the reshaped array and print both.

In [18]:
print(reshaped)
print('='*11)
print(reshaped.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


**Q7.** Write a function to reverse this array.
```python
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
def reverse(arr):
    print(arr[::-1])

reverse(arr)

[9 8 7 6 5 4 3 2 1]


## Practice 4: Higher Dimensions

**Q8.** Create a 3D NumPy array with shape (2, 3, 4) containing numbers from 1 to 24.

In [22]:
arr3d = np.array(range(1,25))
new = np.reshape(arr3d, (2,3,4))
print(new)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


**Q9.** What is the `.ndim` and `.shape` of the array in Q8?

In [23]:
print(new.shape)
print(new.ndim)

(2, 3, 4)
3


## Practice 5: Indexing and Slicing

**Q10.** Create an array from 0 to 9 and extract elements from index 2 to 6.

In [28]:
arr = np.array(range(0,10))
print(arr)
print(arr[2:7])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]


**Q11.** Given a 2D array, retrieve the second row and the third column.

```python
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1,2])

6


## Practice 6: Array Operations

**Q12.** Create two arrays of the same shape and perform element-wise addition, subtraction, and multiplication.

In [34]:
mat1 = np.array([[1,2,3],[4,5,6]])
mat2 = np.array([[7,8,9],[10,11,12]])
print(mat1)
print('#'*20)
print(mat2)
print('#'*20)
print(mat1+mat2)
print('#'*20)
print(mat2 - mat1)
print('#'*20)
print(mat1*mat2)

[[1 2 3]
 [4 5 6]]
####################
[[ 7  8  9]
 [10 11 12]]
####################
[[ 8 10 12]
 [14 16 18]]
####################
[[6 6 6]
 [6 6 6]]
####################
[[ 7 16 27]
 [40 55 72]]


**Q13.** Compute the dot product of:
```python
a = np.array([1, 2])
b = np.array([3, 4])
```

In [35]:
a = np.array([1, 2])
b = np.array([3, 4])
print(a.dot(b))
print('#'*20)
print(b.dot(a))

11
####################
11


## Practice 7: Mathematical Functions
**Q14.** Use NumPy to compute the square root, exponential, and logarithm of each element in:
```python
arr = np.array([1, 4, 9, 16])
```

In [38]:
arr = np.array([1, 4, 9, 16])
print(np.sqrt(arr))
print("#"*20)
print(np.exp(arr))
print("#"*20)
print(np.log(arr))

[1. 2. 3. 4.]
####################
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
####################
[0.         1.38629436 2.19722458 2.77258872]


## Practice 8: Boolean Indexing and Filtering
**Q15.** Create an array of 10 random integers between 1 and 100. Filter out the even numbers.

In [42]:
arr = np.random.randint(1,101,size=10)
print(arr)
print('#'*20)
print(arr%2 == 0)
print('#'*20)
arr[arr%2 == 0] = 0
print(arr)

[13  3  4 22 50 55 59 44  7 79]
####################
[False False  True  True  True False False  True False False]
####################
[13  3  0  0  0 55 59  0  7 79]
